### ISSUE TITLE
El personaje acumula el alpha cuando es golpeado muchas veces

### ISSUE THREAD

**Issue by GisTypical** [Chappie21/Misteria-Kaverna-Aventura#21]
La hipótesis es que el personaje es golpeado antes de que se acabe la animación del `alpha`, por lo que acumula el mismo.

```js
// Enemy.js  ln: 16
config.scene.tweens.add({
    targets: player,
    alpha: 0.5,
    duration: 200,
    repeat: 3,
    yoyo: true
});
```

**Comment by JoseAIG** [comment]
Finalizado agregando .on('complete', ()=>{...}) Despues de la descripcion del tween
